### ISSUE TITLE
IgnoreGas does not ignore gas anymore

### ISSUE THREAD

**Issue by Mike19700** [mhendriks/P1-Dongel-ESP32#15]
After downloading the latest DSMRindexEDGE.html the variable IgnoreGas is not used anymore. I see the Gas field on the Dashboard again. I don't have gas anymore for 6 years now and for me it is a totally waste of space in the dashboard. ;-)

**Comment by mhendriks** [comment]
@Mike19700

Did you use this [Frontend.json]( https://github.com/mhendriks/P1-Dongel-ESP32/blob/master/data/Frontend.json)

with this setting:

`"IgnoreGas": true,`

Please clear browser cache too.

**Comment by Mike19700** [comment]
Thanks. This one can be closed. I forgot the comma after true. 😅
Keep up the good work.
