### ISSUE TITLE
Feature request: P1 sensor for Home Assistant that reports daily water usage

### ISSUE THREAD

**Issue by marcel-st** [mhendriks/P1-Dongel-ESP32#21]
currently there is only a metric sensor that reports total water usage for Home Assistant.
It would be beneficial for dashboards to have a sensor that reports daily water usage and resets to zero every night.

Is this possible?

**Comment by mhendriks** [comment]
the dongle (API) expose the water meter position/counter. This is regardless of the period.
The best way is to use HA for the periodic reports.

for example this kind of config.

utility_meter:  
  waterverbruik_kwartier:
    source: sensor.watermeter_total
    cycle: quarter-hourly
  waterverbruik_uur:
    source: sensor.watermeter_total
    cycle: hourly
  waterverbruik_dag:
    source: sensor.watermeter_total
    cycle: daily    
  waterverbruik_week:
    source: sensor.watermeter_total
    cycle: weekly
  waterverbruik_maand:
    source: sensor.watermeter_total
    cycle: monthly
  waterverbruik_kwartaal:
    source: sensor.watermeter_total
    cycle: quarterly
  waterverbruik_jaar:
    source: sensor.watermeter_total
    cycle: yearly
