### ISSUE TITLE
MQTT Broken

### ISSUE THREAD

**Issue by abrondijk** [mhendriks/P1-Dongel-ESP32#23]
MQTT appears to be broken on the latest firmware release (v4.8.6).

Just received the hardware so this is from the pov of a "clean" install.
Upon entering the MQTT settings (i.e. hostname, username, password & interval) and hitting save, the fields get cleared again and no topics are published to the broker.
I did also notice that the POST requests made upon hitting save end up timing out.

Installing the previous release (v4.8.5) works fine.

Unrelated to this issue:
I also noticed the device being a lot less responsive on v4.8.6.
Loading the actual pages are fine but it takes a lot more time to for the data to be retrieved on the dashboard compared to v4.8.5.

**Comment by mhendriks** [comment]
Thanks for mentioning this issue. 

Due to a bug in the 4.8.6 version the dongle reboots when one of the mqtt settings where changed. That is why the response is slow.

This is solved in the 4.8.6b version. Please try this one with /remote-update?version=4.8.6b
