### ISSUE TITLE
MQTT interval sometimes changes to 0 when making changes

### ISSUE THREAD

**Issue by jeroenrnl** [mhendriks/P1-Dongel-ESP32#26]
When making changes on the configuration page, the MQTT interval sometimes changes itself to `0`, which has left me puzzled why not data is coming out of the system anymore a few times.

**Comment by mhendriks** [comment]
when using the 4.8.6 firmware this "strange" behaviour should be solved. The mqtt logic is refactored in this version.

**Comment by jeroenrnl** [comment]
I'm on  4.8.5 now, 4.8.6 isn't showing up as an available version so far. I'll keep an eye on it the next few days.

**Comment by jeroenrnl** [comment]
I have tried changing settings a few times after updating to 4.8.6 and haven't seen the issue anymore. Thanks for fixing!
