### ISSUE TITLE
No dayly reset

### ISSUE THREAD

**Issue by RobvanderDoes** [mhendriks/P1-Dongel-ESP32#29]
Since the 4.8.7 update the dayly usage (both water & electricity) is no longer dayly: the count goes on from the previous day (no reset to zero at 00.00h).

**Comment by mhendriks** [comment]
Thanks for noticing. This is a bug :-(
Fixed in the 4.8.8 
update with  -> http://p1-dongle-pro.local/remote-update?version=4.8.8
