### ISSUE TITLE
Home Assistant Auto Discover does not work anymore

### ISSUE THREAD

**Issue by Mike19700** [mhendriks/P1-Dongel-ESP32#31]
The Home Assistant Auto Discover worked for a few weeks but with version 4.8.11 no data got into HA.
I use MQTT explorer to see the data is generated by the dongle.
It could also be an update of HA. I can not figure it out.

**Comment by mhendriks** [comment]
thanks for the hint. Fixed in the updated 4.8.12.
Could be installed right now.
