### ISSUE TITLE
Home assisant auto discovery MQTT topic incorrect

### ISSUE THREAD

**Issue by Runesmacher** [mhendriks/P1-Dongel-ESP32#33]
Hi

The Topic for the water sensor in Home assistant with MQTT seems to be incorrect.
Dongle v4.8.14.

The topic should be changed to water_delivered in the auto discovery

![image](https://github.com/mhendriks/P1-Dongel-ESP32/assets/979451/1c309dac-fa73-4b44-a29c-57f5437a1428)
![image](https://github.com/mhendriks/P1-Dongel-ESP32/assets/979451/6058d537-8b44-475a-860a-8434392d45a4)

**Comment by mhendriks** [comment]
@Runesmacher 
I checked it with my current version 4.8.14 b2807 ... looks okay.

<img width="1077" alt="Screenshot 2024-02-04 at 12 25 37" src="https://github.com/mhendriks/P1-Dongel-ESP32/assets/4169609/a87752af-bd0d-4868-bfbc-ecedf6d7fb4a">

**Comment by Runesmacher** [comment]
I have a smart water, gas and electricity meter that all feed trough the Electricity meter, i think that is where the issue stems from.
MQTT send different topics then what HASS is sent as autodiscover:

https://github.com/mhendriks/P1-Dongel-ESP32/blob/7303b3bf7d601df998bc7440a684b0d6187a8c2a/_Water.ino#L8-L17

https://github.com/mhendriks/P1-Dongel-ESP32/blob/7303b3bf7d601df998bc7440a684b0d6187a8c2a/MQTT.ino#L78

**Comment by mhendriks** [comment]
Ah yes this is the problem, sloppy error :-( Thanks for noticing me!
It is changed to the water topic in version 4.8.15 ... now available for update :-)

<img width="539" alt="Screenshot 2024-02-04 at 21 41 44" src="https://github.com/mhendriks/P1-Dongel-ESP32/assets/4169609/ec00b329-8356-4970-8320-2bb762d9a79f">

**Comment by Runesmacher** [comment]
Can confirm it is fixed with 4.8.15.

Thanks!
