### ISSUE TITLE
Feature Request: SSL for MQTT

### ISSUE THREAD

**Issue by jeroenst** [mhendriks/P1-Dongel-ESP32#35]
At this moment there is no option for MQTT over SSL.

Can this be integrated?

**Comment by mhendriks** [comment]
correct. It is added to the backlog :-)

**Comment by jeroenst** [comment]
Is there any progress on this feature?

**Comment by mhendriks** [comment]
no, not yet. The solution is simple but there is not enough program space left to implement the option. I will make a compiler option to enable the sMQTT connection ... the none tsl connection will not work in this version. This is an ugly solution but it is the most feasible at the moment. I will do this within a couple of days.

**Comment by mhendriks** [comment]
Jeroen, There are updates. 
P1 Ethernet Pro: http://eth-dongle-pro.local/remote-update?version=4.8.17TLS
P1 Dongle Pro : http://p1-dongle-pro.local/remote-update?version=4.8.17TLS

Note: mqtt is always with TSL ... so unsecure mqtt isn't supported by this version.

**Comment by jeroenst** [comment]
Hi!

Thank you, I will test this next week.

**Comment by jeroenst** [comment]
I can confirm SSL works. Thank you!
