### ISSUE TITLE
Can't compile source, header files missing

### ISSUE THREAD

**Issue by jeroenst** [mhendriks/P1-Dongel-ESP32#39]
I tried to compile this software with Arduino IDE, but i'm missing the header files

"hw_profile_ultra.h", "hw_profile_p1_eth.h", "hw_profile_p1_pro.h"

Where can I find those?

**Comment by mhendriks** [comment]
those are shared between other projects and therefore outside the project ... but added them couple of secs ago.

https://github.com/mhendriks/P1-Dongel-ESP32/tree/master/conf
