### ISSUE TITLE
When Verzend MQTT Berichten (Sec.) is set to 0 no messages are send to MQTT

### ISSUE THREAD

**Issue by jeroenst** [mhendriks/P1-Dongel-ESP32#40]
When Verzend MQTT Berichten (Sec.) is set to 0 no messages are send to MQTT. I would expect that when 0 is configured there is no rate limit active and all messages are send without any limit instead of nothing.

**Comment by mhendriks** [comment]
correct 
0 = off
1 = fastest (direct after p1 data has been successfully read) ... for v5 meters
10s is fastest for v2/3/4 meters
