### ISSUE TITLE
When using basic-auth parameter in DSMRsettings Frontend settings (partly) not working?

### ISSUE THREAD

**Issue by HanSjak** [mhendriks/P1-Dongel-ESP32#61]
In Frontend I specified IgnoreInjection => True. The dashboard doesn't show "Teruglevering" as intended.
After using basic-auth parameter in DSMRsettings adding name and password my dashboard changed as if the IgnoreInjection is set to False.

Uploading DSMRsettings without name/password gave me back my original Frontend setting.

**Comment by mhendriks** [comment]
I was able to reproduce it once. After a browser refresh it was gone and I couldn't reproduce it anymore.

I expect it's because of the browser cache,

**Comment by HanSjak** [comment]
Sorry! I should have tested that. Everything is ok after browser refresh.
Thank you!
