### ISSUE TITLE
Ignoreinjection: true in Frontend.json has no effect?

### ISSUE THREAD

**Issue by HanSjak** [mhendriks/P1-Dongel-ESP32#64]
Busy with upgrading to v 4.9.1 and setting basic-auth/pass in Settings a couple of weeks ago. Now I realized that the dashboard shows injection data while my Frontend settings were the way that they should not be visible:
{
	"ShowVoltage": true,
	"Injection": false,
	"Phases": 3,
	"Fuse": 25,
	"cdn": true,
	"GasAvailable": true,
	"HideInitial": false,
	"Act_Watt": false,
	"AvoidSpikes": true,
	"IgnoreInjection": true,
	"IgnoreGas": false,
	"i18n": "nl"
}
Is there something wrong with this set?
One of the two meter readings for injection shows the value 0,097 but changed never. May be this triggers the injection data on the dashboard?

**Comment by mhendriks** [comment]
Did you remove the DSMRindexEDGE.html after upgrading to 4.9.1? The dongle wel download the latest index file after removing.

**Comment by HanSjak** [comment]
Thanks for quick response!
No. 
You mean deleting that file in "Bestandsbeheer"?

**Comment by mhendriks** [comment]
correct, just remove it in "Bestandsbeheer" and refresh the browser once or twice.

**Comment by HanSjak** [comment]
OK, it works again as expected! Thanks!
