### ISSUE TITLE
Telegram on port 82 does not work anymore V4.9.9

### ISSUE THREAD

**Issue by Mike19700** [mhendriks/P1-Dongel-ESP32#65]
Since the update to V4.9.9 the telegram port 82 for Domoticz does not show any data.
I went back to version 4.9.4+3414 (13/09/2024)

**Comment by mhendriks** [comment]
thanks for noticing.

Strange ... It is an issue.
I recompiled it (same SDK) and changed the position of the forward telegram function in the flow. Shouldn't make a difference but it does.

4.9.10 version is available and port 82 is working again. (only for the p1 dongle pro)

**Comment by Mike19700** [comment]
It works again.
Thanks for the quick service.

**Comment by Mike19700** [comment]
It works again.
Thanks for the quick service.
